---
title: "Lombardy vs WA Plots"
date: "`r format(Sys.Date(), '%A %b %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE, warning=FALSE}
library(CoV19)
```

```{r italy_plot, message=FALSE, warning=FALSE}
my_plot(italy, "Lombardia", "2020-03-10")
```

```{r wa_plot, message=FALSE, warning=FALSE}
x <- subset(world, region=="Washington US")
# tmp <- x[1,]
# tmp$date <- as.Date("2020-04-04")
# tmp[1,!colnames(tmp) %in% c("date", "region")] <- NA
# tmp$positive <- 7984; tmp$death <- 308
# x <- rbind(x, tmp)
reg <- "Washington US"
p <- my_plot(x, reg) + xlim(as.Date("2020-03-01"), Sys.Date())
p <- add_vline(p, "restaurants close", "2020-03-16")
p <- add_vline(p, "12 days past restaurants closed", "2020-03-28", linetype="dashed")
p <- add_vline(p, "stay at home order", "2020-03-23")
p
```

```{r}
b=subset(states, region=="WA")
tmp=diff(b$total.tests)
plot(b$date[-1], zoo::rollapply(tmp,7,mean,fill=NA),type="l",ylab="tests (7-day average)", xlab="")
par(new=TRUE)
tmp=diff(b$positive)/diff(b$total.tests)
tmp[b$date[-1]<as.Date("2020-03-03")] <- NA
plot(b$date[-1], 100*zoo::rollapply(tmp,7,mean,na.rm=TRUE,fill=NA),yaxt="n", ylab="", ylim=c(0,20), type="l", lwd=2, col="blue")
axis(4)
title("WA 7-day (rolling) averages")
legend("topleft", c("# of tests (left)", "% positive (right)"), lwd=c(1,2), col=c("black", "blue"))
```

```{r world_plot, message=FALSE, warning=FALSE}
reg = unique(world$region[str_detect(world$region, "Washington US")])
reg <- reg[-1*(40:42)]
for(i in reg){
  if(max(subset(world, region==i)$positive)<100) next
  p <- my_plot(world, i) + xlim(as.Date("2020-03-01"), Sys.Date())
  if(!is.null(p)) plot(p)
}
```



