Update #17 After another week, the cases in Lombardy are going slowly down, but we are seeing some interesting patterns.  Remember, noone has seen how a Covid-19 epidemic looks like when it is stopped by a lockdown except in Hubei province China. That data is very noisy and the lockdown was very severe, much more so than in Lombardia. 

For the past weeks, it's been an up and down with very slow decline for the number of new cases in Lombardy. The cases show an interesting 7-day cycle (weekly). The peaks are happening around the weekends so it does not seem to be a reporting issue (i.e. low reporting on weekend). What seems likely is that people are doing something on a weekly basis that is causing the peaks. It could be going to work (essential workers) or socializing in groups (breaking the quarantine). A similar weekly cycle is also seen in the case reporting from Sweden and NY. Figuring out what is causing this cycle will be important for the epidemiologists. Whatever is causing these weekly peaks is clearly driving extra infections (and thus extra deaths).

In WA, the Dept of Health is now providing a cleaned table of the cumulative cases and deaths by country. This is fantastic because the daily reported data (before they go back and assign cases and deaths to the right days) was a huge mess. The cleaned data is much nicer. In the WA data, we also see some cycling go on. Since the state is trying harder to crack down on weekend gatherings, I'm guessing that the epidemiologists are tying that cycling to weekend behavior (rather than essential workers' weekly schedules). Hopefully we don't see a big peak in cases after the Easter and Passover holidays. That would be rather tragic.
                                                                                    There are some interesting patterns are happening in the states. Florida and Louisiana, which seemed like powder kegs, actually looks to be past their peaks. While Alabama, Mississippi, and Texas are big unknowns. No sign of the new cases starting to pause there yet at all.

On the east coast, New York and New Jersey look like they are just past the peak while Conneticutt, Pennesylvania, and Deleware show the tell-tale high variance suggestive of being in the peak. Massachusetts is weird. Its data just don't look like the nearby states. Hard to know what's going on there. Things look promising in the midwest, with Ohio, Wisconsin, Indiana, and Illinois at or just past peaks. 

On the west coast, Oregon and Washington have both driven down the new cases curve quite quickly. Washington looks like it peaked 3rd week of March and Oregon one week later. California looks to have just past its peak, 2 weeks after Washington. However California is very big, and probably should split into north and south for reporting.
