Update #9 I was worried yesterday that the drop in cases in WA was just a blip, due perhaps to testing or reporting delays. I was expecting cases to be up today to compensate, but I didn't expect the jump we saw in WA the last 2 days. There were 627 news cases yesterday and 493 today. Our previous high was 269. However averaged over the last 6 days, our rate of growth is still dropping---though not for long if we get jumps like this. In Lombardy, new cases also jumped up today and yesterday but they were still much below the high of 3,251 new cases per day. After a few days of leveling, hospitalization numbers that went up today and yesterday too.

My takehome from today is that we still have much to learn about the effect of stay at home orders on this epidemic. The response of numbers in Lombardy has had many similarities to what was seen in Hubei (the drop 10-12 days after lockdown) but the new cases have not yet started a slow decline towards 0 like they did in Hubei. 

I'm not going to speculate right now about what is happening. We just have to wait and watch (and hope). Also there are many unknown data issues with the new cases reports so I don't want to read too much into daily fluctuations. I am more interested in longer multi-day trends that are less influenced by short-term ups and downs.

Instead I'm going to talk about a cool modeling and visualization project released by UW: http://covid19.healthdata.org/

This is a model by the UW Institute for Health Metrics and Evaluation. It uses information about how the disease spreads and mortality rates along with the reported deaths to forecast deaths, hospitalizations, and critical cases (ICU). This is overlaid on the total hospital bed and ICU capacity for each state. They forecast that if we maintain current mitigations that we will peak at April 16-20 and latest April 24. I've take an image of the forecast and will see how it does as we go along.

I have not dug into their model yet, but note that the curve shown is for a controlled epidemic. An epidemic that got started and then through mitigation, we drive the R0 below 1 and snuffed out the epidemic. We have not seen this successfully done except in China and South Korea. We don't know if this is possible in other countries. This is why Lombardy is so important. By watching Lombardy, we will find out if they can do what is shown in the UW models. Can Lombardy stop their CoV-19 epidemic by driving R0 below 1 through a lockdown?

So what's the other way that an epidemic is stopped? It can be stopped though 'herd immunity'---the fraction of immunity at which the disease R0 naturally becomes less than 1 (because an infected person doesn't come in contact with enough susceptible people). The the herd immunity level for CoV-19 is like 25% on the low end (R0=1.4) with 50% eventually getting infected. That means once 25% are immune, the number infected starts to decline. If 50% get infected (after the epidemic is all done), that would mean a shocking number of deaths. 7 million (in WA) * 0.50 (infected) * 0.01 (Infected fatality rate) = 35,000. That's a lot of people and the hospitals would be overwhelmed and no longer able to help other people during the epidemic. We don't want that option.

In contrast, the projected deaths in the UW model for WA is 1429---for an epidemic stopped via driving the R0 below 1 through lockdown (extreme social distancing). If the infection fatality rate is 1% overall, then 1429 deaths means ca 1429/0.01 = 142900 infections. Note, most of these infections are not tested; infected does not mean 'positive case'. 142900 is ca 2% of the WA population, which is much much better than 50%. But that means driving the R0 below 1 though mitigation (aka lockdown) not through herd immunity.

And we don't know yet if any western countries can do it. In theory, lockdown should work....