WA has a new website for the coronavirus response. Go there for information and  follow the instructions regarding social distancing. Lot of good info for what is open and closed and how to get help. https://coronavirus.wa.gov/
  
Update #4.  The rate of growth in Lombardy (my comparison region for WA) continues to slowly decline at about 6% per day. Rate of growth is now 12.5% (1.125) per day down from 20% per day when the full lockdown started on March 11th. So numbers are still going up, but they are going up slower. Yeah, the curve is being bent (by staying at home)! I had some comments that I should look at deaths instead of cases because that would be better data. I didn't do that in the beginning since it made me a bit quesy. But I added those today and the rate of growths in deaths is also dropping but seems to lag the cases by about 4 days, which you'd expect since there is a lag between being diagnosed and dying.

In WA, our rate also continues to drop. We are now at 16% per day increase (1.159) down from 18% (1.185) two days ago. So our rate of growth has dropped 7% a day over the last two days. That's not much time so the overall drop rate might be different. But it is in line with what we see with Lombardy after their lockdown. For WA, the rate of growth in deaths is slower than the rate of growth in cases; 12% per day versus 16%. We are ramping up testing, so I assume that difference reflects the ramp up in testing affecting the growth rate of cases. Anyhow, in both cases, the rate of growth is going down.

Govenor Inslee announced today that based on what they are seeing with numbers with hospital admissions and visits, that we don't need to go into a more aggressive lockdown. Hopefully, WA stays disciplined about limiting all non-essential social contact and following the directions from officials so we don't have to go into full-on lockdown. 

I hope you can get out for a walk, hike or a paddle while the weather is good---but don't carpool. :) 
