Update #5 Lockdowns

The information we have on how reported cases (the info that I have for WA) respond to a lockdown is from Wuhan (see attached figure). Yellow is the reported positives while blue is actual point of infection (it takes time to develop symptoms).  You can see that for the first 12 days the number of cases kept going up and rapidly. And because of the way exponential growth works, the number of new cases keeps going up each day every if the rate of growth is slowing. In Wuhan, suddenly at day 12 the number of new positives leveled off. We do not know what will happen in Italy, but everyone is watching and hoping that the same thing will happen, that new cases will level off after 12 days (or so).

Italy is 10 days into their lockdown. Lockdown started a couple days earlier in Lombardy, but my understanding is that real restrictions with restaurants and pubs closed started March 11th. So right now they are in the teeth of the crisis. Yes the rate of growth is still slowly declining, now down to 1.115, but numbers go up every day. The last three days, the new cases have gone up 2171, 2380, and 3251---even though the RATE of growth is still slowly declining. That is how exponential growth works. But the prayer is that, like in Wuhan, in 2-3 more days the number of daily new cases will start declining. The videos of what is the hospitals are dealing with and the exhaustion on the health care workers faces is really hard to watch (I watched some news reports on BBC yesterday).  But of course, the vast vast majority of people are just chilling at home. It is just that a small fraction of millions of people is still a really big number.

What's happening with WA. Our rate of growth in cases continues to decline--even as we ramp up testing. With more testing, you expect more cases but even with that happening, the rate of growth is slowing. The mitigations to reduce community contacts are working! Though it would be really nice if more people who are out recreating (walking Green Lake) took the 6 foot distancing more seriously. 

How to deal with the ramp up in testing? Many people have commented about this on my posts. I am completely aware of this problem, but I do not have a good solution. Some have asked why don't you look at the ratio of positives to number of tests. Definitely you do not want to do that! That only works if the testing is random--you go out to the community, do a straitified random sample of the population. The tests we are doing are not random. These are people who are getting a test because they fit the testing criteria (they are showing symptoms) and have a note from their doctor or they are in the hospital in respiratory distress. The fraction of positives could stay constant as the number of infected (and number of tests) goes through the roof. 

I don't have the number of people being admitted for respiratory distress. The state epidemiologists have that information and that is guiding decisions about mitigations. There are very good modelers advising the governor and they have much better data than I have. What we can do as individuals is to diligently follow the state health department's instructions. It may be the case that a stronger lockdown is needed, though if I had to guess, I say that first they'll lockdown recreation areas more. Like close the parks. If people will not voluntarily keep distant when walking around Green Lake, eg, you close Green Lake. The governor also reported that based on highway numbers King County has greatly retricted movement, but other areas of the state have not. Travel over the Tacoma Narrows bridge is only down 20% versus much higher reductions on 520 and I-90 bridges. Figuring out how to get more compliance outside of King County is probably high on the list (is my guess) based on the governor's press conference. 

How epidemics spread during lockdowns (semi or full).

The goal of the lockdown is to reduce the number of contacts and slow the rate of growth. Our social groups are networks (think of like a web). You have a group that you interact with a lot (the people you live with), next you have the people you associate with frequently (co-workers, family and friends you visit often), and then all the people you interact with the community (by going to gatherings). In normal life, something that spreads like CoV is basically 'panmictic'. It acts as if the population were one big well-mixed population. In a lockdown, you try to make the disease more like a locally spread disease--a disease that only spreads to close contacts. In China, that's what they found after the lockdown. The disease would spread in a local group (family unit = people who live together) and then hop to another family unit. This is different than panmictic spread where the disease appears everywhere and increases at a similar rate whereever you test. In local spread, one family will all get it but the next family will be disease free. At for awhile until a family to family hop happens, and that 'for awhile' is what you are going for. Slow it down.

But there is a point at which it is impossible to switch the system to locally spread. When the fraction infected is low, it works. Many family units have no one infected. Remember that many young people, the infection is asymptomatic. It's the fraction of infected not the fraction showing symptoms (and getting tested) that matters.  Let's say that on average each family+friend unit is 10 (your family + whoever you are still interacting with). If the infection rate is 1%, then on average the chance that no one in that unit is infected is 1-0.99^10=0.10. So 10% of the units, on average, have an infected person in the unit. If the infection rate is 5%, then on average 1-0.95^10=0.40 or 40% have an infected person. So that means even after you imposed lockdown, 40% of people are still exposed to the disease because someone in their unit is infected. So as you can see, the effectiveness of a lockdown depends on the infection rate being low.

Let's look at different family+friend unit sizes (FUS) for 1% and 5% infection throughout the community.

FUS
10 1% = 10% units infected, 5% = 40% infected
 7 1% =  7% units infected, 5% = 30% infected
 5 1% =  5% units infected, 5% = 23% infected
 4 1% =  4% units infected, 5% = 19% infected
 3 1% =  3% units infected, 5% = 14% infected
 2 1% =  2% units infected, 5% = 10% infected
 
 A few takehomes.
 
1) The sooner you limit the number of close contacts you have (by keeping 6 feet, not going to other people's houses, and not gathering), the more effective social distancing will be. You need to reduce your contact size before the disease is spread in your community not after.

2) Your contact size is only as small as that of the person with the largest contacts. So if you are having close contact (living with, regularly getting within 6 feet of) with someone with a large contact size, you contact size is the same as theirs.

                                                                                                      Some daily listening and reading:                   
For those needing to be calmed and reassured: Cuomo's morning report: https://www.youtube.com/watch?v=Sdae4JxM9gI  (I have been watching this before facing the days numbers).
The Hammer and the Dance: https://medium.com/@tomaspueyo/coronavirus-the-hammer-and-the-dance-be9337092b56

------------------
Although the growth rate in Lombardy region (my comparison region for WA) continues to decline, it is declining slowly (about 5% per day). Remember the analogy about slowing down the train? The train takes a long long time to slow down. There is so much momentum built up. And the thing is that when you have no vaccine, you have no brakes. The only thing you can do is take your foot off the gas and let friction do its thing. Even as you are slowing, you are still going forward at a scary rate. The region saw its highest daily deaths since the epidemic began. The deaths were three times higher than when they started their lockdown. Mathematically this is what is expected. If the rate keeps slowing at 5% per day, the numbers will still in another week. 

                                                                                                      HOWEVER, Lombardy (and all of Italy) are coming up on the 12 days since full lockdown and based on what happened in China, we would expect that a big drop in the rate is coming because the 80% quantile on the incubation period is about 12 days. The outer range of incubation is about 27 days, but most incubation periods are much shorter. But western lockdowns are different. The military is not on the roads enforcing a full lockdown. So the lockdown will certainly be less effective, but we just don't know yet. The world's epidemiologists are watching Italy and especially Lombardy.
                                                                                                      
                                                                                                      
                                                                                                      
                                                                                                      3) If your contact size is large or you are regularly having close contact with other social units---social distancing is not possible for all occupations---then try to limit spread to your social unit (family or whoever you live with). It is just like when someone in the house has a cold. Isolating that person (sleep in a different room, use a different bathroom, use one set of dishware, etc) and being hyper about sanitizing can prevent the cold from spreading it to the rest of the family. But in this case, you don't know if you have it or not because so many are asymptomatic. If you have to go out into the community and have close contacts, assume that you will get it. Doctors working with CoV-19 patients practice this at home and have been able to not infect their families.
