Update #6 Today I socially distanced (from K and the dog) by making an R package to download the data on CoV-19 so I could play with it better and make graphs.  Feel free to copy (fork), make plots, etc. https://eeholmes.github.io/CoV19/

In my last post, I said that Hubei saw its new cases going up (a lot) every day post lockdown, and then suddenly at 12 days post lockdown the new cases dropped? Lombardy region is now 11-13 days* out from full lockdown. Today the new cases in Lombardy HALVED!! Just like in Hubei. *I'm not precisely sure the day they started 'must stay home' lockdown and closed businesses in Lombardy. It was Mar 11 in all of Italy, but I think in Lombardy it was a day earlier. Not sure. Numbers in the hospitals in Lombardy will still go up. New cases are still coming in. In Hubei, the numbers in hospitals doubled (roughly) after new cases started declining. The healthcare workers are in a ferocious battle right now. But today was a good sign. The hospitals probably still have the worst ahead, which is really hard to fathom, but the lockdown seems to be working.

In WA, we had fewer new cases than yesterday but also quite a bit less testing. News reported that testing will focus on health care workers and those who need to go to the hospital. But yesterday was high tests and higher numbers, so perhaps it evens out. In anycase, the rate of growth of new cases (averaged over 6 days) is still edging downward at about 5% like it did in Lombardy. We are now at 1.14. That's kind of interesting in itself since our 'lockdown' is more like a slowdown. We have 5-6 more days to see the real effect of our mitigations. Hopefully like in Lombardy, we'll see a big drop in new cases. 
But remember that there is much much more 'momentum' in the system than you would think. Cases went up 444 to 48741 (active cases) in Hubei from lockdown to when the active cases started to decline. Note, many of those were not in the hospital. I didn't look up the hospitalization rate for Hubei (fraction of active cases in hospital). In Lombardy, 60% of positives are hospitalized and 6% of active positives are in the ICU (ventilator). The fraction hospitalized has been high like that throughout. It maybe that testing is focused on those who show up at the hospital (so pretty severe cases). WA does not report the numbers of positives that are in the hospital.

Today it was reported that the lockdown is getting stricter in Italy and people are not allowed to exercise outside. I'm guessing like in WA people were using the allowance to exercise outside as a way gather in groups. Yesterday, I read that the police visited some parks to try to get people to stop gathering. I won't be suprised if we see more restrictions or closures of recreation areas in WA. Sigh. 

