Update #8. As I wrote this morning, Lombardy new cases dropped and new deaths dropped. Yeah! The average new cases is holding steady below 2000 for the last 4 days but it hasn't started declining towards 0. In Hubei, new cases did the same thing. Fluctuated at 30% of the peak for 5 days and then started declining at ca 10% per day towards 0. So another day or so to see if Lombardy shows the same pattern.

In WA, we are 9 days out from when Govenor Inslee closed all the restaurants, pubs and recreation programs. There were mitigations before that (employees encouraged to work at home), but March 16th was the big change. Today we saw a very large decline in new cases. Only 111 new cases which is over a 50% drop from the previous three days. I would normally be estatic, however the WA Dept of Health is reporting that it is having technical difficulties with its reporting database. Over the last two days, the state is releasing its numbers later and later in the day. So I'm going to hold off on any exclamation marks until I see if the numbers get revised tomorrow. Note, King County reported new cases that are 40% down from the peak, so maybe I'm being overly cautious with my exclamation marks.

I am also watching NY. NY will experience the highest number and will have their peak soonest. All the states have much to learn from seeing how mitigations efforts in NY affect the epidemic's trajectory. For the second day in a row, the number of new cases has been around 5000 per day. This is after five straight days of shocking increases in new cases (note that was also happening while testing was ramping up). Govenor Cuomo issued a 'stay at home' order on March 20 and NYC schools closed on March 16. It doesn't seem like enough time for the stay at home order to have an effect, only 5 days. Perhaps the leveling from earlier mitigations (closing schools, encouraging people to stay home).

So much has happened in the last week. We (the world) has learned a lot about the effect of mitigations on CoV-19 spread. A week ago, we only had Hubei's example, and their lockdown worked but it was very strict. Now we also have Lombardy's example. They used travel restrictions early on which reduced the number of tourists, but they waited a relatively long time to close restaurants, pubs and recreation areas. From when their lockdown started, there were ca 400 hospitalized and 12 days later when the new cases stopped increasing, hospitalizations were over 10,000. That is obviously has been a huge strain on their health care system, but the epidemic was stopped. Now it's been long enough that we are started to see evidence that lockdowns are working in CA and WA.

CA and WA are no longer the states with the most cases; they each have 2000-2500 cases. NY has by far the most with over 30,000. NJ is second with ca 5000. FL, LA, IL, MA, and MI will pass WA (and CA) by the weekend if trends continue.

